# Generated by Django 5.2.4 on 2025-08-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('clt_name', models.CharField(max_length=64)),
                ('clt_email', models.EmailField(max_length=64)),
                ('clt_phone', models.CharField(max_length=15)),
                ('sell_name', models.CharField(max_length=64)),
                ('sell_email', models.EmailField(max_length=64)),
                ('sell_phone', models.CharField(max_length=15)),
                ('comments', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('MXN', 'Mexican Pesos'), ('USD', 'Dollars')], default='MXN', max_length=16)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Bank transfer')], default='cash', max_length=16)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=18, max_digits=10)),
                ('warranty_months', models.IntegerField(default=0)),
                ('products', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
