# Generated by Django 5.2.5 on 2026-05-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='audit_trail',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('MXN', 'Pesos Mexicanos'), ('USD', 'Dolares')], default='MXN', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta de crédito/débito'), ('transfer', 'Transferencia bancaria')], default='cash', max_length=16),
        ),
    ]
