# Generated by Django 5.2.5 on 2026-05-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_audit_trail_alter_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='property',
            field=models.CharField(choices=[('residential', 'Residencial'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('government', 'Govierno / Institucional'), ('other', 'Otro')], default='residential', max_length=16),
        ),
    ]
